### ISSUE TITLE
Batch size of realcustom++

### ISSUE THREAD

**Issue by irsLu** [Corleone-Huang/RealCustomProject#2]
This is amazing work for IP, and I have a question about batch size of realcustom++. As we may see, you say realcustom++ uses 8 A100 GPUs for 160,000 iterations (Sec 4.1). And the authors of IP-Adapter say training IP-Adapter maybe need at least 1,000,000 iterations with batch size 8 and 8 GPU. So I would like to ask if you use a larger batch size to make the model converge with so few iterations？

**Comment by Corleone-Huang** [comment]
> This is amazing work for IP, and I have a question about batch size of realcustom++. As we may see, you say realcustom++ uses 8 A100 GPUs for 160,000 iterations (Sec 4.1). And the authors of IP-Adapter say training IP-Adapter maybe need at least 1,000,000 iterations with batch size 8 and 8 GPU. So I would like to ask if you use a larger batch size to make the model converge with so few iterations？

Hi, thanks for your interests. As for SDXL, we first train RealCustom++ on 512 resolution for 60000 iteration with the batch size of 12, and then further train the model for another 100000 iteration with the batch size of 4. Actually, the model performs already ok after further train on 1024 for around 20000 iteration.

The reason why RealCustom++ converges fast is that we simply use the MLP to project ALL reference image features (the same reason why we have a higher subject similarity). IP-Adapter-XL use Qformer to downsample the image feature, and the Qformer is known for hard to converge.

**Comment by Corleone-Huang** [comment]
> This is amazing work for IP, and I have a question about batch size of realcustom++. As we may see, you say realcustom++ uses 8 A100 GPUs for 160,000 iterations (Sec 4.1). And the authors of IP-Adapter say training IP-Adapter maybe need at least 1,000,000 iterations with batch size 8 and 8 GPU. So I would like to ask if you use a larger batch size to make the model converge with so few iterations？

Hi, we release all the model and code in https://github.com/bytedance/RealCustom. The approval process for open-source of the company is just too long (T_T).
